version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rentguy_dev
      - SECRET_KEY=your-secret-key-change-in-production
      - FIRST_SUPERUSER_EMAIL=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=changeme
      - FIRST_SUPERUSER_FIRST_NAME=Admin
      - FIRST_SUPERUSER_LAST_NAME=User
    depends_on:
      - db
    networks:
      - rentguy-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentguy_dev
    ports:
      - '5432:5432'
    networks:
      - rentguy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  rentguy-network:
    driver: bridge

volumes:
  postgres_data:
