version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rentguy_dev
      - SECRET_KEY=your-secret-key-change-in-production
      - FIRST_SUPERUSER_EMAIL=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=changeme
      - FIRST_SUPERUSER_FIRST_NAME=Admin
      - FIRST_SUPERUSER_LAST_NAME=User
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rentguy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentguy_dev
    ports:
      - '5432:5432'
    networks:
      - rentguy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rentguy_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  rentguy-network:
    driver: bridge

volumes:
  postgres_data:
