[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]
aptPkgs = ["libpq-dev", "build-essential"]

[phases.install]
cmds = [
  "if [ -d \"frontend\" ]; then cd frontend && npm install; fi",
  "if [ -d \"backend\" ]; then cd backend && pip install -r requirements.txt; fi"
]

[phases.build]
cmds = [
  "mkdir -p /app/static",
  "if [ -d \"frontend\" ]; then cd frontend && npm run build && cp -r dist/* /app/static/; fi",
  "if [ -d \"backend\" ]; then mkdir -p /app/backend && cp -r backend/* /app/backend/; fi",
  "chmod +x /app/backend/start.sh"
]

[start]
cmd = "cd /app/backend && ./start.sh"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
