# Railway deployment configuration for RentGuy application
# Following Semantic Seed Venture Studio Coding Standards V2.0

[build]
builder = "nixpacks"
buildCommand = "echo 'Building both frontend and backend services'"

[deploy]
startCommand = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60

[env]
DATABASE_URL = "${DATABASE_URL}"
SECRET_KEY = "${SECRET_KEY}"
FIRST_SUPERUSER_EMAIL = "${FIRST_SUPERUSER_EMAIL}"
FIRST_SUPERUSER_PASSWORD = "${FIRST_SUPERUSER_PASSWORD}"
FIRST_SUPERUSER_FIRST_NAME = "${FIRST_SUPERUSER_FIRST_NAME}"
FIRST_SUPERUSER_LAST_NAME = "${FIRST_SUPERUSER_LAST_NAME}"
