version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rentguy_dev
      - SECRET_KEY=your-secret-key
      - FIRST_SUPERUSER_EMAIL=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=changeme
      - FIRST_SUPERUSER_FIRST_NAME=Admin
      - FIRST_SUPERUSER_LAST_NAME=User
    depends_on:
      - db
    networks:
      - rentguy-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentguy_dev
    ports:
      - "5432:5432"
    networks:
      - rentguy-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - rentguy-network

networks:
  rentguy-network:
    driver: bridge

volumes:
  postgres_data:
